#!/usr/bin/env bash

SOURCES="$(ls -1 /etc/shepard)"

for source in "$SOURCES"; do
  herd start "$source"
done

function stop() {
  SOURCES="$(ls -1 /etc/shepard)"
  for source in "$SOURCES"; do
    herd stop "$source"
  done
}

function shutdown() {
  stop
}

trap stop SIGSTOP
trap shutdown SIGPWR

PS=$(ps x | grep -v ps | grep -v init | grep -v grep | awk '{print $5}')

function run() {
  for ps in "$PS"; do
     wait "$ps" && herd start "$ps"
  done
}

while true; do
  run &
  wait
done
